# Generated by Django 3.2.4 on 2021-06-25 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_mobile_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id',
                 models.BigAutoField(auto_created=True,
                                     primary_key=True,
                                     serialize=False,
                                     verbose_name='ID')),
                ('msg', models.CharField(max_length=100)),
                ('timezone', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField()),
            ],
        ),
    ]
