# Generated by Django 3.2.4 on 2021-07-27 11:00

from django.db import migrations, models

import accounts.validators


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='timezone',
            field=models.CharField(
                max_length=50,
                validators=[accounts.validators.validate_timezone]),
        ),
    ]
